name: First Workflow

on: 
  push:  
    branches: 
      - main
      
jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: print a welcome  messege
      run: echo "Welcome to our first GitHub Action Workflow!"

    -  name: Checkout reposatory
       uses: actions/checchout@v7.0.0

    - name: List reposatory files
      run: ls -la 
